# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "debian_opscode"

  config.vm.network "private_network", ip: "172.12.8.162"

  config.vm.provision "shell", path: "../_provision/provision.sh"

  # DEVELOPMENT MODE
  # config.vm.provision "file", source: "fig.yml", destination: "fig.yml"
  # config.vm.provision "file", source: "Dockerfile", destination: "Dockerfile"
  # config.vm.provision "file", source: "supervisord.conf", destination: "supervisord.conf"
  # pkg_cmd = "fig run web npm install ; fig up -d"
  # config.vm.provision "shell", inline: pkg_cmd, run: "always"


end
